---
- name: verify
  hosts: all
  become: true
  vars:
    goss_version: v0.3.13
    goss_arch: amd64
    goss_bin: /usr/local/bin/goss
    goss_sha256sum: "sha256:eb3522ff9682736ff61e2ad114de227de98debcf8a03ca66fcda3917577313e0"
    goss_test_directory: /tmp/molecule/goss
    goss_format: documentation
  tasks:
    - name: Download and install Goss
      get_url:
        url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
        dest: "{{ goss_bin }}"
        checksum: "{{ goss_sha256sum }}"
        mode: 0755

    - name: Create Molecule directory for test files  # noqa risky-file-permissions
      file:
        path: "{{ goss_test_directory }}"
        state: directory

    - name: Find Goss tests on localhost
      find:
        paths: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}"
        patterns:
          - "test[-.\\w]*.yml"
          - "test_host_{{ ansible_hostname }}[-.\\w]*.yml"
        excludes:
          - "test_host_(?!{{ ansible_hostname }})[-.\\w]*.yml"
        use_regex: true
        file_type: any
      delegate_to: localhost
      register: test_files
      changed_when: false
      become: false

    - name: debug
      debug:
        msg: "{{ test_files.files }}"
        verbosity: 3

    - name: Copy Goss tests to remote  # noqa risky-file-permissions

      copy:
        src: "{{ item.path }}"
        dest: "{{ goss_test_directory }}/{{ item.path | basename }}"
        follow: true
      with_items:
        - "{{ test_files.files }}"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_*.yml"  # noqa no-changed-when
      register: test_files

    - name: Execute Goss tests
      command: "{{ goss_bin }} -g {{ item }} validate --format {{ goss_format }}"  # noqa no-changed-when
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      failed_when: false

    - name: Display details about the Goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
