---
dependency:
  name: galaxy
platforms:
  - name: dokku-install-test-vm
    box: ${PLATFORM_BOX}
    provider_options:
      driver: '"qemu"'
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: goss
  directory: ../resources/tests
driver:
  name: vagrant
  provider:
    name: ${PROVIDER_NAME}
    type: ${PROVIDER_TYPE}
    options:
      memory: ${PROVIDER_MEMORY}
      cpus: 2
      #####
      management_network_name: vagrant-libvirt-molecule
      management_network_address: '192.168.127.0/24'
