---
- name: Get uptime information
  ansible.builtin.shell: /usr/bin/uptime
  register: result
  changed_when: false

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result

