---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Run the dokku.install role
      include_role:
        name: dokku.install
      vars:
        DOKKU_SERVER_HOST_NAME: dokku-vouch-proxy
