---
- name: converge
  hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Run dokku.install
      include_role:
        name: dokku.install
      vars:
        DOKKU_SERVER_HOST_NAME: "dokku-install-test-vm"

    - name: Run dokku.configure
      include_role:
        name: dokku.configure
      vars:
        DOKKU_SERVER_HOST_NAME: "dokku-install-test-vm"

    - name: Run dokku.apps.vouch.create
      include_role:
        name: dokku.apps.vouch.create
      vars:
        DOKKU_SERVER_HOST_NAME: dokku-vouch-proxy
        use_letsencrypt:  false
        letsencrypt_type: "staging"
        vouch_whitelist:  "john.smith@gmail.com,sarah-jane.smith@gmail.com"
        contact_email:    "dokku-letsencrypt-maintainer@phlummox.dev"
        oauth_provider_secret: |
          OAUTH_PROVIDER=google
          OAUTH_CLIENT_ID=1220-blah-blah.apps.googleusercontent.com
          OAUTH_CLIENT_SECRET=8YDxxxxxxxxxxxxxxxxxxxxA
