name: build-vagrant-box

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VAGRANT_VERSION: "2.2.14"
      LIBVIRT_PLUGIN_VERSION: "0.0.1"
      PACKER_VERSION: "1.7.0"

    steps:

    - name: set path
      run: |
        set -euo pipefail
        set -x

        mkdir -p ~/.local/bin
        echo "PATH=${HOME}/.local/bin:${PATH}" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    #- name: Cache vagrant boxes
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.vagrant.d/boxes
    #    key: ${{ runner.os }}-vagrant-${{ hashFiles('ansible-roles/Makefile') }}
    #    restore-keys: |
    #      ${{ runner.os }}-vagrant-

    - name: Cache pip download dir
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip*
        key: ${{ runner.os }}-pipcache-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-pipcache-

    - name: Cache python libs
      uses: actions/cache@v2
      with:
        path: |
          ~/.local
        key: ${{ runner.os }}-piplibs-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-piplibs-

    - name: Install vagrant and packer
      run: |
        set -euo pipefail
        set -x

        PACKER_URL="https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
        wget $PACKER_URL
        unzip packer_${PACKER_VERSION}_linux_amd64.zip
        sudo mv packer /usr/local/bin

        packer --version

    - name: Install build dependencies
      run: |
        set -euo pipefail
        set -x

        ./provision-test-machine.sh

    - name: Install/build python-based dependencies
      run: |
        set -euo pipefail
        set -x

        cd install-ansible
        make py_prereqs

    - name: run build
      run: |
        set -euo pipefail
        set -x

        #cd packer-boxmaker-config
        #make packer-build

# vim: ts=2 sw=2 et :
