name: vagrant-test

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VAGRANT_VERSION: "2.2.14"
      LIBVIRT_PLUGIN_VERSION: "0.0.1"

    steps:

    - name: set path
      run: |
        set -euo pipefail
        set -x

        mkdir -p ~/.local/bin
        echo "PATH=${HOME}/.local/bin:${PATH}" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    #- name: Cache vagrant boxes
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.vagrant.d/boxes
    #    key: ${{ runner.os }}-vagrant-${{ hashFiles('ansible-roles/Makefile') }}
    #    restore-keys: |
    #      ${{ runner.os }}-vagrant-

    - name: Cache pip download dir
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip*
        key: ${{ runner.os }}-pipcache-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-pipcache-

    - name: Cache python libs
      uses: actions/cache@v2
      with:
        path: |
          ~/.local
        key: ${{ runner.os }}-piplibs-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-piplibs-

    - name: Install vagrant
      run: |
        set -euo pipefail
        set -x

        VAGRANT_URL="https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb"
        dir=`mktemp -d tmp-downloaded-vagrant-deb-XXXXX`
        curl -L "${VAGRANT_URL}" > $dir/vagrant.deb
        sudo apt install $PWD/$dir/vagrant.deb

    - name: install libvirt dependencies
      run: |
        set -euo pipefail
        set -x

        sudo apt install -y --no-install-recommends \
            libvirt-bin                 \
            libvirt-dev                 \
            openssh-client              \
            qemu-kvm                    \
            qemu-utils                  \
            sshpass                     \
            time                        \
            virtinst                    \
            wget                        \
            xz-utils                    \
            zip

        sudo systemctl start libvirtd
        sudo systemctl status libvirtd

        sudo adduser $USER libvirt
        sudo adduser $USER kvm

    - name: Install basic python packages
      run: |
        set -euo pipefail
        set -x

        python3 .ci-scripts/get-pip.py

        pip3 install --user --upgrade \
            pip         \
            pip-tools   \
            virtualenv  \
            wheel

    - name: Show tool versions
      run: |
        set -euo pipefail
        set -x

        gcc     --version
        pip3    --version
        python3 --version
        ssh     -V
        vagrant --version
        virsh   --version

    - name: Install libvirt plugin for vagrant
      run: |
        set -euo pipefail
        set -x

        LIBVIRT_PLUGIN_URL="https://github.com/phlummox/vagrant-in-vagrant/releases/download/v${LIBVIRT_PLUGIN_VERSION}/vagrant.d.tgz"

        curl -L "${LIBVIRT_PLUGIN_URL}" | tar x -z -C ~

        vagrant plugin list | grep vagrant-libvirt


    #- name: test libvirt
    #  run: |
    #    set -x
    #    set -euo pipefail

    #    id
    #    virsh list --all
    #    #./virsh-test.sh

    - name: test libvirt plugin
      run: |
        set -x
        set -euo pipefail

        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1


        sudo iptables --list
        sudo iptables -P INPUT ACCEPT
        sudo iptables -P OUTPUT ACCEPT
        sudo iptables -P FORWARD ACCEPT
        sudo iptables -F

        sudo iptables --list

        sudo systemctl restart libvirtd

        origdir=$PWD
        tmpdir=`mktemp -d libvirt-test-XXXXXX`
        cd $tmpdir

        vagrant box add --provider libvirt generic/ubuntu1804
        vagrant box add --provider libvirt phlummox/vagrant-in-vagrant

        # can't use kvm driver on GitHub CI,
        # use qemu
        cat > Vagrantfile <<EOF
        Vagrant.configure("2") do |config|
          config.vm.box         = "phlummox/vagrant-in-vagrant"
          #config.ssh.password   = "vagrant"
          #config.ssh.username   = "vagrant"
          #config.ssh.insert_key = false
          config.vm.provider :libvirt do |lv|
            lv.driver = 'qemu'
            lv.cpus   = 1
            lv.memory = 792
            #lv.username = "vagrant"
            #lv.password = "vagrant"
            #lv.id_ssh_key_file = nil
            #lv.nic_model_type = "virtio"
            #lv.nested = true
            lv.graphics_type = "none"
          end
        end
        EOF

        sudo su -l $USER -c "set -ex; export CI=$CI; cd $PWD; pwd; id; ls -al /var/run/libvirt/libvirt-sock; vagrant up --no-provision --debug --provider libvirt"

        #vagrant ssh -- ls -a /

        false

    #- name: create ssh keys
    #  run: |
    #    set -x
    #    set -euo pipefail
    #    #ssh -V
    #    #ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""
    #    #cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    #    #ls -al ~/.ssh
    #    #: "show id"
    #    #id
    #    #: "existing sshd config"
    #    #sudo grep -n ^ /dev/null /etc/ssh/sshd_config
    #    #: "configure ssh"
    #    #cat > sshd_config <<EOF
    #    #AllowAgentForwarding yes
    #    #AllowTcpForwarding yes
    #    #X11Forwarding yes
    #    #PermitTunnel yes
    #    #PermitEmptyPasswords yes
    #    ## pass locale information
    #    #AcceptEnv LANG LC_*
    #    ## override default of no subsystems
    #    #Subsystem	sftp	/usr/libexec/sftp-server
    #    #PermitRootLogin yes
    #    #UsePAM yes
    #    #PasswordAuthentication no
    #    #ChallengeResponseAuthentication no
    #    #EOF
    #    #sudo mv -f sshd_config /etc/ssh/sshd_config
    #    #sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
    #    #sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
    #    #ssh_opts="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    #    #ssh -vvvv $ssh_opts localhost ls / || true
    #    #sudo ls -al /var/log || true
    #    #sudo cat /var/log/system.log | grep -i -E 'auth|ssh' || true
    #    #sudo grep ssh /var/log/secure.log || true
    #    #false

    - name: Install/build python-based dependencies
      run: |
        set -euo pipefail
        set -x

        cd install-ansible
        make py_prereqs


    - name: Run molecule tests
      # force colors for molecule and ansible, even
      # though not tty
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
      run: |
        set -euo pipefail
        set -x

        sudo su -l $USER -c "set -ex; export CI=$CI; cd $PWD/ansible-roles; pwd; make run_tests_libvirt"

    #    ## ansible-lint all files
    #    #./lint-the-files.sh
    #    ## also do plain yamllint
    #    #yamllint -c .yamllint $(find `ls | grep -v install-ansible` -name '*.yml' -o -name '*.yaml')

    #    #set +e
    #    #ls -al ~/.local/lib/python*/site-packages/ || true

# vim: ts=2 sw=2 et :
