name: vagrant-test

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VAGRANT_VERSION: "2.2.14"
      LIBVIRT_PLUGIN_VERSION: "0.0.1"

    steps:

    - name: set path
      run: |
        set -euo pipefail
        set -x

        mkdir -p ~/.local/bin
        echo "PATH=${HOME}/.local/bin:${PATH}" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    #- name: Cache vagrant boxes
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.vagrant.d/boxes
    #    key: ${{ runner.os }}-vagrant-${{ hashFiles('ansible-roles/Makefile') }}
    #    restore-keys: |
    #      ${{ runner.os }}-vagrant-

    - name: Cache pip download dir
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip*
        key: ${{ runner.os }}-pipcache-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-pipcache-

    - name: Cache python libs
      uses: actions/cache@v2
      with:
        path: |
          ~/.local
        key: ${{ runner.os }}-piplibs-${{ hashFiles('install-ansible/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-piplibs-

    - name: Provision for testing
      run: |
        set -euo pipefail
        set -x

        ./provision-test-machine.sh

    #- name: test libvirt
    #  run: |
    #    set -x
    #    set -euo pipefail

    #    id
    #    virsh list --all
    #    #./virsh-test.sh

    #- name: create ssh keys
    #  run: |
    #    set -x
    #    set -euo pipefail
    #    #ssh -V
    #    #ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""
    #    #cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    #    #ls -al ~/.ssh
    #    #: "show id"
    #    #id
    #    #: "existing sshd config"
    #    #sudo grep -n ^ /dev/null /etc/ssh/sshd_config
    #    #: "configure ssh"
    #    #cat > sshd_config <<EOF
    #    #AllowAgentForwarding yes
    #    #AllowTcpForwarding yes
    #    #X11Forwarding yes
    #    #PermitTunnel yes
    #    #PermitEmptyPasswords yes
    #    ## pass locale information
    #    #AcceptEnv LANG LC_*
    #    ## override default of no subsystems
    #    #Subsystem	sftp	/usr/libexec/sftp-server
    #    #PermitRootLogin yes
    #    #UsePAM yes
    #    #PasswordAuthentication no
    #    #ChallengeResponseAuthentication no
    #    #EOF
    #    #sudo mv -f sshd_config /etc/ssh/sshd_config
    #    #sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
    #    #sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
    #    #ssh_opts="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    #    #ssh -vvvv $ssh_opts localhost ls / || true
    #    #sudo ls -al /var/log || true
    #    #sudo cat /var/log/system.log | grep -i -E 'auth|ssh' || true
    #    #sudo grep ssh /var/log/secure.log || true
    #    #false

    - name: Install/build python-based dependencies
      run: |
        set -euo pipefail
        set -x

        cd install-ansible
        make py_prereqs


    - name: Run molecule tests
      # force colors for molecule and ansible, even
      # though not tty
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
      run: |
        set -euo pipefail
        set -x

        sudo su -l $USER -c "set -ex; export PY_COLORS=$PY_COLORS; export ANSIBLE_FORCE_COLOR=$ANSIBLE_FORCE_COLOR; export CI=$CI; export PATH=$PATH; cd $PWD/ansible-roles; pwd; make run_tests_libvirt"

    #    ## ansible-lint all files
    #    #./lint-the-files.sh
    #    ## also do plain yamllint
    #    #yamllint -c .yamllint $(find `ls | grep -v install-ansible` -name '*.yml' -o -name '*.yaml')

    #    #set +e
    #    #ls -al ~/.local/lib/python*/site-packages/ || true

# vim: ts=2 sw=2 et :
